====== (This is the documentation for SDL3, which is under heavy development and the API is changing! [https://wiki.libsdl.org/SDL2/ SDL2] is the current stable version!) ======
= SDL_GetSurfaceColorKey =

Get the color key (transparent pixel) for a surface.

== Syntax ==

<syntaxhighlight lang='c'>
int SDL_GetSurfaceColorKey(SDL_Surface *surface,
                    Uint32 *key);
</syntaxhighlight>

== Function Parameters ==

{|
|'''surface'''
|the [[SDL_Surface]] structure to query
|-
|'''key'''
|a pointer filled in with the transparent pixel
|}

== Return Value ==

Returns 0 on success or a negative error code on failure; call
[[SDL_GetError]]() for more information.

== Remarks ==

The color key is a pixel of the format used by the surface, as generated by
[[SDL_MapRGB]]().

If the surface doesn't have color key enabled this function returns -1.

== Version ==

This function is available since SDL 3.0.0.

== Related Functions ==

:[[SDL_BlitSurface]]
:[[SDL_SetSurfaceColorKey]]

----
[[CategoryAPI]]


