name: Build

on: [push, pull_request]

jobs:
  Build:
    name: Build all pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pandoc
    - name: Configure CMake
      run: |
        cmake -S .github -B build
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure -j$(nproc)
    - name: Upload artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        path: |
          build/wikidir/**
